version: "3"

services:
  manage-slots:
    build: .
    volumes:
      - .:/root/manage-slots
    container_name: manage-slots
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://manage-slots-mongo/manage-slots
      - SECRET_KEY=123456
      - APP_PORT=3000
      - APP_NAME=manage-slots
    ports:
      - 3000:3000
    networks:
      - slots-network

  mongo:
    image: bitnami/mongodb:latest
    container_name: manage-slots-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /tmp/mongo:/bitnami
    networks:
      - slots-network
      
networks:
  slots-network:
    driver: bridge
